# Generated by Django 4.0.1 on 2022-01-26 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fips', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
